[package]
name = "rust-lightning-bitcoinrpc"
version = "0.0.1"
authors = ["Matt Corallo <git@bluematt.me>"]
build = "build.rs"

[dependencies]
bitcoin = "0.15"
bitcoin-bech32 = "0.7"
bitcoin_hashes = "0.1"
lightning = { git = "https://github.com/rust-bitcoin/rust-lightning" }
lightning-invoice = "0.1"
secp256k1 = "0.11"
hyper = "0.12"
tokio-io = "0.1"
tokio-fs = "0.1"
tokio-codec = "0.1"
futures = "0.1"
serde = "1"
serde_json = "1"
serde_derive = "1"
rand = "0.4"
tokio = "0.1"
bytes = "0.4"
base64 = "0.9"

[build-dependencies]
cc = "1.0"

[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"
