[package]
name = "rust-lightning-bitcoinrpc"
version = "0.0.1"
authors = ["Matt Corallo <git@bluematt.me>"]
build = "build.rs"

[dependencies]
bitcoin = "0.13"
lightning = { path = "../rust-lightning" }
secp256k1 = "0.9"
hyper = "0.12"
tokio-io = "0.1"
tokio-fs = "0.1"
tokio-codec = "0.1"
futures = "0.1"
serde_json = "1"
rand = "0.4"
tokio = "0.1"
bytes = "0.4"
base64 = "0.9"

[build-dependencies]
gcc = "0.3"
